version: '2'

services:
  app:
    image: 'app:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8081:8081"
      - "8090:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:alpine'
    container_name: postgres-0
    environment:
      - DEBUG=true
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
      - DB_EXTENSION="uuid-ossp"